name: CI

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: NPM Install
        run: npm i

      - name: Check symbols
        run: |
          npm list --depth=0 ts-node
          npm run checksymbols
